[package]
name = "rustik"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = "0.15.6"
nalgebra = "0.31.1"
urdf-rs = "0.6.5"
simba = "0.7.2"
